### ISSUE TITLE
Looping example incorrect

### ISSUE THREAD

**Issue by AllenWilliamson** [theproductiveprogrammer/html-in-js#1]
The example in the section "Loop over table data" is incorrect or at least incomplete. Using the code as-is would produce unwanted commas.

For example:
```
const data = ['One', 'Two', 'Three'];
console.log(`<ul>
    ${data.map(item => `<li>${item}</li>`)}
</ul>`);
```

Output:
```
<ul>
    <li>One</li>,<li>Two</li>,<li>Three</li>
</ul>
```

A simple fix would be to join the array after mapping.
```
const data = ['One', 'Two', 'Three'];
console.log(`<ul>
    ${data.map(item => `<li>${item}</li>`).join('')}
</ul>`);
```

**Comment by theproductiveprogrammer** [comment]
You're right - corrected the example. Thank you.
